# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/plugin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/plugin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/plugin/CMakeFiles /home/ubuntu/plugin/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/plugin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AclTester

# Build rule for target.
AclTester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AclTester
.PHONY : AclTester

# fast build rule for target.
AclTester/fast:
	$(MAKE) -f CMakeFiles/AclTester.dir/build.make CMakeFiles/AclTester.dir/build
.PHONY : AclTester/fast

#=============================================================================
# Target rules for targets named PluginTester

# Build rule for target.
PluginTester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PluginTester
.PHONY : PluginTester

# fast build rule for target.
PluginTester/fast:
	$(MAKE) -f CMakeFiles/PluginTester.dir/build.make CMakeFiles/PluginTester.dir/build
.PHONY : PluginTester/fast

#=============================================================================
# Target rules for targets named hashtest

# Build rule for target.
hashtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hashtest
.PHONY : hashtest

# fast build rule for target.
hashtest/fast:
	$(MAKE) -f CMakeFiles/hashtest.dir/build.make CMakeFiles/hashtest.dir/build
.PHONY : hashtest/fast

#=============================================================================
# Target rules for targets named p

# Build rule for target.
p : cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p
.PHONY : p

# fast build rule for target.
p/fast:
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/build
.PHONY : p/fast

AclTester.o: AclTester.c.o
.PHONY : AclTester.o

# target to build an object file
AclTester.c.o:
	$(MAKE) -f CMakeFiles/AclTester.dir/build.make CMakeFiles/AclTester.dir/AclTester.c.o
.PHONY : AclTester.c.o

AclTester.i: AclTester.c.i
.PHONY : AclTester.i

# target to preprocess a source file
AclTester.c.i:
	$(MAKE) -f CMakeFiles/AclTester.dir/build.make CMakeFiles/AclTester.dir/AclTester.c.i
.PHONY : AclTester.c.i

AclTester.s: AclTester.c.s
.PHONY : AclTester.s

# target to generate assembly for a file
AclTester.c.s:
	$(MAKE) -f CMakeFiles/AclTester.dir/build.make CMakeFiles/AclTester.dir/AclTester.c.s
.PHONY : AclTester.c.s

Plugin.o: Plugin.c.o
.PHONY : Plugin.o

# target to build an object file
Plugin.c.o:
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/Plugin.c.o
.PHONY : Plugin.c.o

Plugin.i: Plugin.c.i
.PHONY : Plugin.i

# target to preprocess a source file
Plugin.c.i:
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/Plugin.c.i
.PHONY : Plugin.c.i

Plugin.s: Plugin.c.s
.PHONY : Plugin.s

# target to generate assembly for a file
Plugin.c.s:
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/Plugin.c.s
.PHONY : Plugin.c.s

PluginTester.o: PluginTester.c.o
.PHONY : PluginTester.o

# target to build an object file
PluginTester.c.o:
	$(MAKE) -f CMakeFiles/PluginTester.dir/build.make CMakeFiles/PluginTester.dir/PluginTester.c.o
.PHONY : PluginTester.c.o

PluginTester.i: PluginTester.c.i
.PHONY : PluginTester.i

# target to preprocess a source file
PluginTester.c.i:
	$(MAKE) -f CMakeFiles/PluginTester.dir/build.make CMakeFiles/PluginTester.dir/PluginTester.c.i
.PHONY : PluginTester.c.i

PluginTester.s: PluginTester.c.s
.PHONY : PluginTester.s

# target to generate assembly for a file
PluginTester.c.s:
	$(MAKE) -f CMakeFiles/PluginTester.dir/build.make CMakeFiles/PluginTester.dir/PluginTester.c.s
.PHONY : PluginTester.c.s

hashtest.o: hashtest.c.o
.PHONY : hashtest.o

# target to build an object file
hashtest.c.o:
	$(MAKE) -f CMakeFiles/hashtest.dir/build.make CMakeFiles/hashtest.dir/hashtest.c.o
.PHONY : hashtest.c.o

hashtest.i: hashtest.c.i
.PHONY : hashtest.i

# target to preprocess a source file
hashtest.c.i:
	$(MAKE) -f CMakeFiles/hashtest.dir/build.make CMakeFiles/hashtest.dir/hashtest.c.i
.PHONY : hashtest.c.i

hashtest.s: hashtest.c.s
.PHONY : hashtest.s

# target to generate assembly for a file
hashtest.c.s:
	$(MAKE) -f CMakeFiles/hashtest.dir/build.make CMakeFiles/hashtest.dir/hashtest.c.s
.PHONY : hashtest.c.s

security_default.o: security_default.c.o
.PHONY : security_default.o

# target to build an object file
security_default.c.o:
	$(MAKE) -f CMakeFiles/AclTester.dir/build.make CMakeFiles/AclTester.dir/security_default.c.o
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/security_default.c.o
.PHONY : security_default.c.o

security_default.i: security_default.c.i
.PHONY : security_default.i

# target to preprocess a source file
security_default.c.i:
	$(MAKE) -f CMakeFiles/AclTester.dir/build.make CMakeFiles/AclTester.dir/security_default.c.i
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/security_default.c.i
.PHONY : security_default.c.i

security_default.s: security_default.c.s
.PHONY : security_default.s

# target to generate assembly for a file
security_default.c.s:
	$(MAKE) -f CMakeFiles/AclTester.dir/build.make CMakeFiles/AclTester.dir/security_default.c.s
	$(MAKE) -f CMakeFiles/p.dir/build.make CMakeFiles/p.dir/security_default.c.s
.PHONY : security_default.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... AclTester"
	@echo "... PluginTester"
	@echo "... edit_cache"
	@echo "... hashtest"
	@echo "... p"
	@echo "... rebuild_cache"
	@echo "... AclTester.o"
	@echo "... AclTester.i"
	@echo "... AclTester.s"
	@echo "... Plugin.o"
	@echo "... Plugin.i"
	@echo "... Plugin.s"
	@echo "... PluginTester.o"
	@echo "... PluginTester.i"
	@echo "... PluginTester.s"
	@echo "... hashtest.o"
	@echo "... hashtest.i"
	@echo "... hashtest.s"
	@echo "... security_default.o"
	@echo "... security_default.i"
	@echo "... security_default.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

